#
#
#
#
#
{0}{}{Preferencias de jogo}
{1}{}{Ajustes de Tela}
{3}{}{Opcoes}


{50}{}{Ajustes de Tela}
{51}{}{Customizado}
{52}{}{Largura}
{53}{}{Altura}
{54}{}{Pronto}
{55}{}{Cancelar}
{56}{}{Fallout precisa reiniciar para aplicar suas alteracoes.}
{57}{}{Você gostaria de reiniciar o Fallout agora?}
{58}{}{Verdadeiro}
{59}{}{Falso}
{60}{}{}


{100}{}{Alta resolucao}
{101}{}{Resolucao}
{102}{}{Cores}
{103}{}{8 Bit}
{104}{}{16 Bit}
{105}{}{32 Bit}
{106}{}{Alterar a arte da barra lateral}
{107}{}{Inverter a lista}
{108}{}{Janela}
{109}{}{Informar tecla de rolagem}
{110}{}{Escala X2}
{111}{}{Freq. atualizacao}

{130}{}{Tecla Window}
{131}{}{Selecionar}
{132}{}{Nome}

{140}{}{Modo do Grafico:}
{141}{}{Basico}
{142}{}{Modo Sfall DirectX 9:}
{143}{}{}

{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}

{147}{}{Direct3D 9}
{148}{}{Vertex Hardware Processing:}
{149}{}{Shader Version 2.0:}

{150}{}{Escala do painel}
{151}{}{Nenhum}
{152}{}{Caber}
{153}{}{Preencher}

{154}{}{Filmes}
{155}{}{Splash}
{156}{}{Ajuda}
{157}{}{Morto}
{158}{}{Slides finais}
{159}{}{Menu principal}

{200}{}{Sfall}
{201}{}{SCALE-TO: RES.}
{202}{}{DX-9 MODE}
{203}{}{Off}
{204}{}{Tela cheia}
{205}{}{Janela}
{206}{}{GPU Blitting}
{207}{}{Esta configuração não tem efeito quando estiver no modo de graficos basico.}

{250}{}{Ignorar o limite de rolagem do PC}
{253}{}{Path Finding Range}
{254}{}{Normal}
{255}{}{Maximo}
{256}{}{Habilitar a neblina de guerra}
{257}{}{Visibilidade da neblina}
{258}{}{Escura}
{259}{}{Clara}

{300}{}{Pressiona a telca A ou ESC para cancelar.}

{500}{}{Configuracoes do Patch de alta resolucao.}
{501}{}{Configure a resolucao da tela, cores e frequencia de atualiacao para o modo tela cheia.}
{502}{}{Configure as cores de saida para tela cheia aqui.}
{503}{}{Configure a taxa de atualização para tela cheia aqui. Informe '0' para a configuração padrao do seu driver.}
{504}{}{Customize a largura da tela clicando na caixa de numero.}
{505}{}{Customize a altura da tela clicando na caixa de numero.}
{506}{}{Habilite ou desabilite o modo Janela.}
{507}{}{No modo janela, esta e a tecla que você vai segurar quando usar o mouse para rolar no jogo e nos mapas.}
{508}{}{Pressione o botão vermelho para escolher outra telca. Ou clique na caixa numeria para informar o codigo de uma tecla virtual.}
{509}{}{O nome da tecla selecionada atualmente.}
{510}{}{Habilitar a escala X2. Isto tambem aumenta a resolucao minima para 1280x960. Se estiver no modo janela, e necessário mais espaco em tela para caber a sua borda.}
{511}{}{Habilite ou Desabilite a Neblina de Guerra. Para uma melhor experiência de jogo, esta opcao pode permanecer habilitada antes de iniciar a jogar.}
{512}{}{Ajuste a intencidade da luz e a visibilidade de terrenos, paredes e cenarios abaixo da neblina em conjunto com a opcao "Olhar para" do mouse.}
{513}{}{Terrenos, Paredes e cenários sempre estarao visiveis e a opcao do mouse "Olhar para" vai funcionar normalmente.}
{514}{}{Floors, walls and scenery will be darkened and unresponsive to Mouse "look at" until discovered.}
{515}{}{Quando habilitado, a opcao de rolar longe do jogador e ilimitada. Isto funciona bem se a Neblina de Guerra estiver habilitada.}
{516}{}{Incremente o numero de busca de nos para extender a distancia percorrida para encontrar o caminho. 20 levels incrementa em 2000 nos.}
{517}{}{2000 nos de 'Encontrar o caminho'(valor original). OBS: Cada level requer um aespaco adicional de 156.25 KB de memoria.}
{518}{}{40 000 nos de 'Encontrar o caminho'. OBS: Requer 3.200.000 bytes (3MB) of memory.}
{519}{}{Ajuste como algumas telas serao exibidas.}
{520}{}{Tamanho original.}
{521}{}{Esticar para caber no tamanho da tela mantendo o o aspecto original da imagem.}
{522}{}{Esticar para caber na tela. OBS: Um espaco será mantido na parte inferior da tela se as legendas estiverem habilitadas.}
{523}{}{Clique abaixo para alternar nas opcoes da barra lateral de quando estiver em jogo.}
{524}{}{Aplicar as alteracoes e sair.}
{525}{}{Sair sem salvar.}

