#
#
#
#
#
{0}{}{Preferências de jogo}
{1}{}{Ajustes de Tela}
{3}{}{Opções}


{50}{}{Ajustes de Tela}
{51}{}{Customizado}
{52}{}{Largura}
{53}{}{Altura}
{54}{}{Pronto}
{55}{}{Cancelar}
{56}{}{Fallout precisa reiniciar para aplicar suas alterações.}
{57}{}{Você gostaria de reiniciar o Fallout agora?}
{58}{}{Verdadeiro}
{59}{}{Falso}
{60}{}{}


{100}{}{Hi-Res}
{101}{}{Resolução}
{102}{}{Cores}
{103}{}{8 Bit}
{104}{}{16 Bit}
{105}{}{32 Bit}
{106}{}{Alterar a arte da barra lateral}
{107}{}{Inverter a lista}
{108}{}{Janela}
{109}{}{Informar tecla de rolagem}
{110}{}{Escala X2}
{111}{}{Freq. atualização}

{130}{}{Tecla Window}
{131}{}{Selecionar}
{132}{}{Nome}

{140}{}{Modo do Gráfico:}
{141}{}{Básico}
{142}{}{Modo Sfall DirectX 9:}
{143}{}{}

{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}

{147}{}{Direct3D 9}
{148}{}{Vertex Hardware Processing:}
{149}{}{Shader Version 2.0:}

{150}{}{Escala do painel}
{151}{}{None}
{152}{}{Fit}
{153}{}{Fill}

{154}{}{Filmes}
{155}{}{Splash}
{156}{}{Ajuda}
{157}{}{Morto}
{158}{}{Slides finais}
{159}{}{Menu principal}

{200}{}{Sfall}
{201}{}{SCALE-TO: RES.}
{202}{}{DX-9 MODE}
{203}{}{Off}
{204}{}{Tela cheia}
{205}{}{Janela}
{206}{}{GPU Blitting}
{207}{}{Esta configuração não tem efeito quando estiver no modo de gráficos básico.}

{250}{}{Ignorar o limite de rolagem do PC}
{253}{}{Alcance para encontrar caminho}
{254}{}{Normal}
{255}{}{Máximo}
{256}{}{Habilitar a Neblina de Guerra}
{257}{}{Visibilidade da Neblina}
{258}{}{Escura}
{259}{}{Clara}

{300}{}{Pressione a tecla A ou ESC para cancelar.}

{500}{}{Configurações do Patch de Hi-Res.}
{501}{}{Configure a resolução da tela, cores e frequência de atualização para o modo tela cheia.}
{502}{}{Configure as cores de saída para tela cheia aqui.}
{503}{}{Configure a taxa de atualização para tela cheia aqui. Informe '0' para a configuração padrão do seu driver.}
{504}{}{Customize a largura da tela clicando na caixa de número.}
{505}{}{Customize a altura da tela clicando na caixa de número.}
{506}{}{Habilite ou desabilite o modo Janela.}
{507}{}{No modo janela, esta é a tecla que você vai segurar quando usar o mouse para rolar no jogo e nos mapas.}
{508}{}{Pressione o botão vermelho para escolher outra tecla. Ou clique na caixa numérica para informar o código de uma tecla virtual.}
{509}{}{O nome da tecla selecionada atualmente.}
{510}{}{Habilitar a escala X2. Isto também aumenta a resolução mínima para 1280x960. Se estiver no modo janela, é necessário mais espaço em tela para caber a sua borda.}
{511}{}{Habilite ou desabilite a Neblina de Guerra. Para uma melhor experiência de jogo, esta opção deve ser habilitada antes de iniciar um jogo pela primeira vez.}
{512}{}{Ajuste a intensidade da luz e a visibilidade de terrenos, paredes e cenários abaixo da neblina em conjunto com a opção "Olhar para" do mouse.}
{513}{}{Terrenos, paredes e cenários sempre estarão visíveis e a opção do mouse "Olhar para" vai funcionar normalmente.}
{514}{}{Terrenos, paredes e cenários serão escurecidos e não irão reagir a opção do mouse "Olhar para" até serem descobertos.}
{515}{}{Quando habilitado, a opção de rolar longe do jogador é ilimitada. Isto funciona bem se a Neblina de Guerra estiver habilitada.}
{516}{}{Incremente o número de busca de nós para estender a distância percorrida para encontrar o caminho. 20 leveis incrementa em 2000 nós.}
{517}{}{2.000 nós de 'Encontrar o caminho'(valor original). OBS: Cada level requer um espaço adicional de 156,25 KB de memória.}
{518}{}{40.000 nós de 'Encontrar o caminho'. OBS: Requer 3.200.000 bytes (3MB) de memória.}
{519}{}{Ajuste como algumas telas serão exibidas.}
{520}{}{Tamanho original.}
{521}{}{Esticar para caber no tamanho da tela mantendo o aspecto original da imagem.}
{522}{}{Esticar para caber na tela. OBS: Um espaço será mantido na parte inferior da tela se as legendas estiverem habilitadas.}
{523}{}{Clique abaixo para alternar as opções de barra lateral da interface de quando estiver em jogo.}
{524}{}{Aplicar as alterações e sair.}
{525}{}{Sair sem salvar.}

